[package]
name = "Chess"
version = "0.1.0"
authors = ["Chili-Bebber <dexter.gaonshatford@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.7"
dirs = "2.0"
[lib]
crate-type = ["cdylib"]
